### PR TITLE
update translations

### PR DESCRIPTION
**Pull request by chris48s**
This PR is here mostly as a reminder.

In both #108 and #109 I am making changes that affect the translations file.

My instinct was to run `make i18n_extract` on each branch and commit the changes to the generate .po files, but I found that the translations weren't up to date so a bunch of other stuff spewed out. This commit is the result of running `make i18n_extract` on `main`.

Just to reduce the merge conflicts, I'm going to say we review those 2 PRs as they stand and then I'll rebase this PR on `main` and merge the result.

How do we go about getting translations updated for this project?

### CODE REVIEW

**Comment by chris48s** [comment]
OK. This PR now accounts for everything on main

**Comment by symroe** [comment]
@chris48s there's a translation service we've used in the past form the Welsh Gov. Hello blod? @pmk01 will know the details.

**Review by symroe — APPROVED** [review]

**Comment by chris48s** [comment]
OK. So it is our responsibility to send text off to the translators, get it back and update the po files?

**Comment by chris48s** [comment]
I've updated a couple of translations here, but the decision from the EC is we don't need to translate the City of London stuff since it is text that is only shown to users in England.

**Review by symroe — APPROVED** [review]

**Pull request merged**
